version: '3'

services:
  app:
    image: sae-ecommerce
    container_name: sae-ecommerce
    build:
      dockerfile: Dockerfile.prod
      context: .
    ports:
      - 3100:3000
    restart: unless-stopped
